$HOSTNAME = "midnightlocomotive.dev"
$BOX = "ubuntu/trusty64"
$IP = "8.0.0.8"
$MEMORY = ENV.has_key?('VM_MEMORY') ? ENV['VM_MEMORY'] : "2048"
$CPUS = ENV.has_key?('VM_CPUS') ? ENV['VM_CPUS'] : "2"
$EXEC_CAP = ENV.has_key?('VM_EXEC_CAP') ? ENV['VM_EXEC_CAP'] : "100"

Vagrant.configure("2") do |config|
  config.vm.hostname = $HOSTNAME
  config.vm.box = $BOX
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.vm.network :private_network, ip: $IP
  config.ssh.forward_agent = true

  config.vm.synced_folder "../../", "/var/www/midnightlocomotive/current", type: "nfs"

  config.vm.provider "virtualbox" do |v|
    v.name = "midnightlocomotive"
    v.customize ["modifyvm", :id, "--cpuexecutioncap", $EXEC_CAP]
    v.customize ["modifyvm", :id, "--memory", $MEMORY]
    v.customize ["modifyvm", :id, "--cpus", $CPUS]
  end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.sudo = true
  #   ansible.playbook = "playbook.yml"
  #   ansible.limit = "vagrant"
  #   ansible.inventory_path = "hosts/vagrant"
  #   ansible.verbose = "vvvv"
  #   ansible.tags = "config"
  #   ansible.raw_arguments  = "--vault-password-file=password.txt"
  # end
end
